"""Added building_type column to users table

Revision ID: 26ad52b4f457
Revises: d49ccd42032c
Create Date: 2025-09-28 16:49:34.154769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26ad52b4f457'
down_revision: Union[str, Sequence[str], None] = 'd49ccd42032c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('building_type_filter', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'building_type_filter')
    # ### end Alembic commands ###
