"""add private_only_filter

Revision ID: 817175bc6141
Revises: 26ad52b4f457
Create Date: 2025-09-29 19:59:51.109408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '817175bc6141'
down_revision: Union[str, Sequence[str], None] = '26ad52b4f457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sent_ads', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.add_column('users', sa.Column('private_only_filter', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'private_only_filter')
    op.alter_column('sent_ads', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
