"""Add filters

Revision ID: d49ccd42032c
Revises: f30f332820ad
Create Date: 2025-09-14 23:51:26.855684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd49ccd42032c'
down_revision: Union[str, Sequence[str], None] = 'f30f332820ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ad_type_filter', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('min_price_filter', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('max_price_filter', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('min_surface_area_filter', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'min_surface_area_filter')
    op.drop_column('users', 'max_price_filter')
    op.drop_column('users', 'min_price_filter')
    op.drop_column('users', 'ad_type_filter')
    # ### end Alembic commands ###
